// 모든 사용자 노출 문자열 (한국어)

export const S = {
  title: '좀비시티',
  subtitle: '친구들과 즐기는 좀비 감염 술래잡기 (2~10인)',
  nickname: '닉네임',
  nicknamePh: '닉네임을 입력하세요',
  createRoom: '방 만들기',
  joinRoom: '입장하기',
  codePh: '방 코드 (예: ABCDE)',
  or: '또는',
  connecting: '연결 중…',
  roomCode: '방 코드',
  copy: '복사',
  copied: '복사됨!',
  copyLink: '링크 복사',
  players: '플레이어',
  ready: '준비',
  readyDone: '준비 완료!',
  waitHost: '방장이 시작하길 기다리는 중…',
  start: '게임 시작',
  needPlayers: '2명 이상 필요',
  needReady: '모두 준비되면 시작!',
  duration: '플레이 시간',
  minutes: (m) => `${m}분`,
  leave: '나가기',
  host: '방장',
  tapToChangeLook: '캐릭터를 눌러 변경',
  // feed
  feedInfected: (n) => `🧟 ${n}님이 좀비가 되었습니다!`,
  feedInfectedBy: (a, b) => `🧟 ${a}님이 ${b}님을 감염시켰습니다!`,
  feedCured: (n) => `💉 ${n}님이 백신으로 치료되었습니다!`,
  feedKilled: (n) => `💀 좀비 ${n}님이 쓰러졌습니다!`,
  feedCrate: '📦 보급품 투하!',
  feedLeft: (n) => `👋 ${n}님이 떠났습니다`,
  feedBack: (n) => `🔌 ${n}님이 돌아왔습니다`,
  // end
  humanWin: '인간 승리!',
  zombieWin: '좀비 승리!',
  aborted: '게임 중단',
  statName: '이름',
  statInfections: '감염',
  statKills: '처치',
  statCures: '치료',
  statSurvived: '생존',
  rematch: '다시 하기',
  toLobby: '로비로',
  waitRematch: '방장을 기다리는 중…',
  // errors / overlays
  errSignal: '서버에 연결할 수 없어요. 잠시 후 다시 시도해 주세요.',
  errNoRoom: '방을 찾을 수 없어요. 코드를 확인해 주세요.',
  errFull: '방이 가득 찼어요. (최대 10명)',
  errStarted: '이미 시작된 게임이에요.',
  errVersion: '게임 버전이 달라요. 새로고침해 주세요.',
  errHostGone: '호스트와의 연결이 끊어져 게임이 종료되었습니다.',
  errConn: '연결에 실패했어요. 다른 네트워크를 시도해 주세요.',
  reconnecting: '연결이 끊겨 재접속 중…',
  hostWaiting: '호스트 연결 대기 중…',
  roomClosed: '방장이 방을 닫았어요.',
  home: '홈으로',
  ok: '확인',
  shareHint: '친구에게 코드나 링크를 공유하세요!',
  zombiePick: (n) => `${n}명 중 좀비가 선택됩니다`,
  touchAttack: '공격',
  touchVaccine: '백신',
};
